name: CD
on:
  release:
    types:
      - published
      - edited
jobs:
  tests:
    name: release to digital ocean
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_IP }}
          username: ${{ secrets.DO_USER }}
          port: ${{ secrets.DO_PORT }}
          key: ${{ secrets.DO_SSHKEY }}
          overwrite: true
          source: .
          target: /opt/app
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_IP }}
          username: ${{ secrets.DO_USER }}
          port: ${{ secrets.DO_PORT }}
          key: ${{ secrets.DO_SSHKEY }}
          script: |
            cd /opt/app
            yarn install
            yarn build
            pm2 reload /opt/app/dist/service.js
